"""initial schema

Revision ID: 9b4d73af0c56
Revises:
Create Date: 2026-08-03 03:46:02.420878
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9b4d73af0c56"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("ok", "retry", "fallback", "failed", name="ai_outcome", native_enum=False),
            nullable=False,
        ),
        sa.Column("needed_clarification", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_calls_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_calls")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "update",
                "delete",
                "restore",
                "tz_change",
                name="audit_action",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_entity", "audit_log", ["entity", "entity_id"], unique=False)
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("event", "task", "routine", name="entry_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("start_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("rrule", sa.String(length=500), nullable=True),
        sa.Column("tz", sa.String(length=64), nullable=False),
        sa.Column("local_time", sa.Time(), nullable=True),
        sa.Column(
            "importance",
            sa.Enum("low", "normal", "high", name="importance", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "persistence",
            sa.Enum("normal", "important", name="persistence", native_enum=False),
            nullable=False,
        ),
        sa.Column("reminders_min_before", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "done", "cancelled", "paused", name="entry_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("google_event_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind <> 'routine' OR rrule IS NOT NULL", name=op.f("ck_entries_routine_has_rrule")
        ),
        sa.CheckConstraint(
            "duration_min IS NULL OR (duration_min > 0 AND duration_min <= 1440)",
            name=op.f("ck_entries_duration_sane"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_entries_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entries")),
    )
    op.create_index(
        "ix_entries_active",
        "entries",
        ["user_id", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_entries_user_id"), "entries", ["user_id"], unique=False)
    op.create_table(
        "tz_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tz_from", sa.String(length=64), nullable=False),
        sa.Column("tz_to", sa.String(length=64), nullable=False),
        sa.Column(
            "changed_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entries_reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tz_changes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tz_changes")),
    )
    op.create_index(op.f("ix_tz_changes_user_id"), "tz_changes", ["user_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tz", sa.String(length=64), nullable=False),
        sa.Column("quiet_from", sa.Time(), nullable=False),
        sa.Column("quiet_to", sa.Time(), nullable=False),
        sa.Column("digest_enabled", sa.Boolean(), nullable=False),
        sa.Column("digest_time", sa.Time(), nullable=False),
        sa.Column("review_time", sa.Time(), nullable=False),
        sa.Column("week_start", sa.SmallInteger(), nullable=False),
        sa.Column("default_snooze_min", sa.Integer(), nullable=False),
        sa.Column("confirm_before_save", sa.Boolean(), nullable=False),
        sa.CheckConstraint("default_snooze_min > 0", name=op.f("ck_user_settings_snooze_positive")),
        sa.CheckConstraint(
            "week_start BETWEEN 0 AND 6", name=op.f("ck_user_settings_week_start_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    op.create_table(
        "occurrences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("planned_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "done",
                "skipped",
                "moved",
                "missed",
                name="occurrence_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("moved_count", sa.Integer(), nullable=False),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["entries.id"],
            name=op.f("fk_occurrences_entry_id_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_occurrences_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occurrences")),
        sa.UniqueConstraint("entry_id", "planned_at_utc", name="uq_occurrence_slot"),
    )
    op.create_index(
        "ix_occurrences_day", "occurrences", ["user_id", "planned_at_utc"], unique=False
    )
    op.create_index(op.f("ix_occurrences_entry_id"), "occurrences", ["entry_id"], unique=False)
    op.create_index(op.f("ix_occurrences_user_id"), "occurrences", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurrence_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fire_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("pre", "main", "repeat", name="notification_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "cancelled",
                "missed",
                name="notification_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("silent", sa.Boolean(), nullable=False),
        sa.Column("sent_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["occurrences.id"],
            name=op.f("fk_notifications_occurrence_id_occurrences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("occurrence_id", "fire_at_utc", "kind", name="uq_notification_slot"),
    )
    op.create_index(
        "ix_notifications_due", "notifications", ["status", "fire_at_utc"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_occurrence_id"), "notifications", ["occurrence_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "active_context",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("occurrence_id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=True),
        sa.Column("expires_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_active_context_notification_id_notifications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["occurrences.id"],
            name=op.f("fk_active_context_occurrence_id_occurrences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_active_context_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_active_context")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("active_context")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_occurrence_id"), table_name="notifications")
    op.drop_index("ix_notifications_due", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_occurrences_user_id"), table_name="occurrences")
    op.drop_index(op.f("ix_occurrences_entry_id"), table_name="occurrences")
    op.drop_index("ix_occurrences_day", table_name="occurrences")
    op.drop_table("occurrences")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_tz_changes_user_id"), table_name="tz_changes")
    op.drop_table("tz_changes")
    op.drop_index(op.f("ix_entries_user_id"), table_name="entries")
    op.drop_index(
        "ix_entries_active", table_name="entries", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("entries")
    op.drop_index("ix_audit_entity", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("ai_calls")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
